spring.application.name=TestePratico



spring.datasource.url=jdbc:postgresql://ep-cool-firefly-anlbfze6-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_9otfzTW7qKYr
spring.datasource.driver-class-name=org.postgresql.Driver




spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true